--
-- PostgreSQL database dump
--

\restrict 4BrPHDkGrQfJZSCltTqtfYCRT2i5Xd82ggWqVws0lb0V4JyhcZisq6IrDNfyNrr

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AnswerOption; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."AnswerOption" (
    id bigint NOT NULL,
    text character varying(200) NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public."AnswerOption" OWNER TO gek;

--
-- Name: AnswerOption_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."AnswerOption" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AnswerOption_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Available tests; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."Available tests" (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    max_attempts integer NOT NULL,
    CONSTRAINT "Available tests_max_attempts_check" CHECK ((max_attempts >= 0))
);


ALTER TABLE public."Available tests" OWNER TO gek;

--
-- Name: Available tests_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."Available tests" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Available tests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Available tests_tests; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."Available tests_tests" (
    id bigint NOT NULL,
    studenttype_id bigint NOT NULL,
    test_id bigint NOT NULL
);


ALTER TABLE public."Available tests_tests" OWNER TO gek;

--
-- Name: Available tests_tests_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."Available tests_tests" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Available tests_tests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Question; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."Question" (
    id bigint NOT NULL,
    text text NOT NULL,
    image character varying(100),
    test_id bigint NOT NULL
);


ALTER TABLE public."Question" OWNER TO gek;

--
-- Name: Question_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."Question" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserAnswer; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."UserAnswer" (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL,
    selected_option_id bigint,
    user_id bigint NOT NULL,
    attempt_id bigint NOT NULL
);


ALTER TABLE public."UserAnswer" OWNER TO gek;

--
-- Name: UserAnswer_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."UserAnswer" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserAnswer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserTestResult; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public."UserTestResult" (
    id bigint NOT NULL,
    score double precision NOT NULL,
    total_questions integer NOT NULL,
    correct_answers integer NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    attempt_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public."UserTestResult" OWNER TO gek;

--
-- Name: UserTestResult_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public."UserTestResult" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserTestResult_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO gek;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO gek;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO gek;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO gek;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO gek;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO gek;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO gek;

--
-- Name: gtests_usertestattempt; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.gtests_usertestattempt (
    id bigint NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed boolean NOT NULL,
    test_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.gtests_usertestattempt OWNER TO gek;

--
-- Name: gtests_usertestattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.gtests_usertestattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gtests_usertestattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    enterprise character varying(150) NOT NULL,
    plot character varying(150) NOT NULL,
    function character varying(150) NOT NULL,
    surname character varying(150) NOT NULL,
    student_type_id bigint
);


ALTER TABLE public.student OWNER TO gek;

--
-- Name: student_groups; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.student_groups (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.student_groups OWNER TO gek;

--
-- Name: student_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.student_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_user_permissions; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.student_user_permissions (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.student_user_permissions OWNER TO gek;

--
-- Name: student_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.student_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test; Type: TABLE; Schema: public; Owner: gek
--

CREATE TABLE public.test (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    time_limit integer,
    image character varying(100)
);


ALTER TABLE public.test OWNER TO gek;

--
-- Name: test_id_seq; Type: SEQUENCE; Schema: public; Owner: gek
--

ALTER TABLE public.test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: AnswerOption; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."AnswerOption" (id, text, is_correct, question_id) FROM stdin;
210	Напряжение	f	54
211	Сопротивление	f	54
212	Силу тока	t	54
213	Мощность	f	54
214	Генератор	f	55
215	Трансформатор	f	55
216	Электродвигатель	t	55
217	Резистор	f	55
218	Уменьшается	f	56
219	Складывается	t	56
220	Не изменяется	f	56
221	Становится нулевым	f	56
222	Одинаков во всех ветвях	f	57
223	Делится по ветвям	t	57
224	Всегда равен нулю	f	57
225	Увеличивается в 2 раза	f	57
226	Вольт	f	58
227	Ампер	f	58
228	Ом	t	58
229	Ватт	f	58
230	Не важно	f	59
231	Нет	f	59
232	Да	t	59
233	Рычагом ручного тормоза в кабине	f	60
234	Нажатием кнопки на панели управления в кабине	t	60
235	Парковочного тормоза нет	f	60
236	Через БРС на напорном клапане	f	61
237	Напрямую в гидравлический бак	f	61
238	через БРС на обратном фильтре	t	61
239	не обязательно	f	62
240	попадание частиц пыли в двигатель вызывает преждевременный износ двигателя	t	62
241	пыль трудно удалить из системы воздухозабора	f	62
242	не обязательно	f	63
243	попадание частиц пыли в двигатель вызывает преждевременный износ двигателя	t	63
244	пыль трудно удалить из системы воздухозабора	f	63
245	посредством БРС на фильтре заливки масла ДВС	t	64
246	заливка обычным способом	f	64
247	через пробку клапанной крышки	f	64
248	с помощью индикации на приборной панели	f	65
249	через заливную трубу	f	65
250	с помощью мерных глазков установленных непосредственно на гидробаке	t	65
251	пневматической тормозной системой	f	66
252	многодисковый с пружинным затормаживанием и с гидравлической разблокировкой	t	66
253	гидравлическая тормозная система с колодочным тормозом	f	66
254	60 Ом	t	67
255	120 Ом	f	67
256	От 60 до 120 Ом	f	67
257	нажатием клавиши на панели управления в кабине	t	68
258	при запуске ДВС	f	68
259	кнопкой на панели управления на трейлере	f	68
260	закрыть загрузочный люк	f	69
261	очистить поверхность от бетона с помощью мойки высокого давления	f	69
262	все вышеперечисленные варианты	t	69
263	выключателем, расположенным в основном электрическом шкафу	t	70
264	нажатием на кнопку аварийной остановки	f	70
265	аварийного режима не предусмотрено	f	70
266	500 м/часов	f	71
267	1000 м/часов	t	71
268	3000 м/часов	f	71
269	1000 м/часов	t	72
270	3000 м/часов	f	72
271	не регламентируется	f	72
272	На основании среднесуточной наработки машины	f	73
273	На основании показаний счетчика моточасов на машине	f	73
274	На основании показаний счетчика моточасов на машине и среднесуточной наработки	t	73
275	10 км/ч	f	74
276	не имеет значения	f	74
277	3 км/ч	t	74
278	470 Н/м	f	75
279	550 Н/м	f	75
280	650 Н/м	t	75
281	500 м/часов	f	76
282	1000 м/часов	f	76
283	3000 м/часов	t	76
284	Допускается использовать масла из наличия на участке	f	77
285	Допускается использовать масла спецификации рекомендованной заводом изготовителем	t	77
286	Все выше перечисленные варианты	f	77
287	280 Бар	f	78
288	420 Бар	f	78
289	450 Бар	f	78
290	12В	f	79
291	24В	t	79
292	36В	f	79
293	открыванием крышки радиатора	f	80
294	с помощью смотрового стекла на расширительном баке	t	80
295	не требует проверки	f	80
296	1 раз в месяц	f	81
297	ежесменно	t	81
298	не требуется	f	81
299	только гидравлического мотора	f	82
300	мотора хода, установленного на мосту	t	82
301	трансмиссией с коробкой передач	f	82
302	гидравлического мотора	f	83
303	ручного топливного насоса	f	83
304	гидравлического топливного насоса высокой подачи	t	83
305	с помощью клавиш панели управления в кабине	t	84
306	с помощью кнопок на интерфейсе оператора	f	84
307	не включаются/выключаются вручную	f	84
308	подняв машину с помощью крюка и потянув	f	85
309	включив аварийный насос, открыв буксировочные краны на насосах хода и медленно потянув машину	t	85
310	машину невозможно отбуксировать, ее можно увезти только на автозвакуаторе	f	85
311	педалями хода вперед и назад	f	86
312	переключателем направления движения на рулевой колонке	t	86
313	с помощью коробки передач	f	86
314	Катушка	f	87
315	Соленоид	f	87
316	Реле	t	87
317	Предохранитель	f	87
318	Раздел гидравлики, изучающий движение жидкостей	f	88
319	Раздел гидравлики, изучающий равновесие жидкостей	t	88
320	Раздел физики о тепловых явлениях	f	88
321	Наука о сжатии газов	f	88
322	Несжимаемая и не имеющая вязкости	t	89
323	Сжимаемая и с высокой вязкостью	f	89
324	Только вода	f	89
325	Любая жидкость под давлением	f	89
326	Давление в жидкости передаётся только по направлению движения	f	90
327	Давление в жидкости передаётся во все стороны одинаково	t	90
328	Давление зависит от плотности жидкости	f	90
329	Давление убывает с глубиной	f	90
330	P = F / S	f	91
331	P = ρ × g × h	t	91
332	P = m × g	f	91
333	P = V × ρ	f	91
334	Отношение динамической вязкости к плотности	t	92
335	Силу трения между слоями жидкости	f	92
336	Способность жидкости сжиматься	f	92
337	Температуру застывания жидкости	f	92
338	Центробежный насос	f	93
339	Шестерённый насос	t	93
340	Вихревой насос	f	93
341	Струйный насос	f	93
342	Низкая стоимость	f	94
343	Работа при высоких давлениях (до 400-500 бар)	t	94
344	Простая конструкция	f	94
345	Не требует обслуживания	f	94
346	Объём жидкости, подаваемый за один оборот вала	t	95
347	Максимальное давление насоса	f	95
348	Полный объём корпуса насоса	f	95
349	Объём масла в баке	f	95
350	Q = V × n	t	96
351	Q = P × S	f	96
352	Q = m × g	f	96
353	Q = ρ × V	f	96
354	Устройство для преобразования механической энергии в гидравлическую	f	97
355	Устройство для преобразования гидравлической энергии в механическую	t	97
356	Устройство для фильтрации масла	f	97
357	Устройство для охлаждения жидкости	f	97
358	Ничем, они взаимозаменяемы	f	98
359	У мотора больше объёмный КПД	f	98
360	У мотора окна на распределителе сдвинуты	t	98
361	У мотора меньший вес	f	98
362	Шестерённый	f	99
363	Радиально-поршневой	t	99
364	Пластинчатый	f	99
365	Аксиально-поршневой	f	99
366	Бар	f	100
367	Паскаль (Па)	t	100
368	Килограмм-сила (кгс)	f	100
369	Атмосфера (атм)	f	100
370	1 бар	f	101
371	5 бар	f	101
372	10 бар	t	101
373	100 бар	f	101
374	Для регулировки расхода жидкости	f	102
375	Для защиты системы от превышения давления	t	102
376	Для фильтрации масла	f	102
377	Для изменения направления потока	f	102
378	Устройство для изменения направления потока жидкости	t	103
379	Устройство для регулировки давления	f	103
380	Устройство для очистки жидкости	f	103
381	Устройство для нагрева жидкости	f	103
382	4 положения, 3 рабочих порта	f	104
383	3 положения, 4 рабочих порта	t	104
384	4 порта, 3 золотника	f	104
385	3 литра в минуту, 4 бара	f	104
386	Пропускает жидкость только в одном направлении	t	105
387	Регулирует давление в системе	f	105
388	Дросселирует поток жидкости	f	105
389	Смешивает два потока жидкости	f	105
390	Рабочее давление должно быть в 3-4 раза меньше разрушающего	t	106
391	Рукав должен иметь металлическую оплётку	f	106
392	Минимальный радиус изгиба не нормируется	f	106
393	Допустимы любые перегибы	f	106
394	Наружный резиновый слой	f	107
395	Внутренний маслостойкий слой	t	107
396	Металлическая оплётка	f	107
397	Промежуточный текстильный слой	f	107
398	Внутренний диаметр и рабочее давление	t	108
399	Только длина рукава	f	108
400	Цвет наружного слоя	f	108
401	Только производитель	f	108
402	Сетчатый фильтр	f	109
403	Бумажный фильтр	t	109
404	Магнитный фильтр	f	109
405	Отстойник	f	109
406	Устройство для ограничения расхода жидкости	t	110
407	Устройство для повышения давления	f	110
408	Устройство для изменения направления потока	f	110
409	Устройство для очистки масла	f	110
410	Для накопления гидравлической энергии и сглаживания пульсаций	t	111
411	Для увеличения давления	f	111
412	Для фильтрации масла	f	111
413	Для нагрева рабочей жидкости	f	111
414	Образование пузырьков пара в жидкости из-за низкого давления	t	112
415	Высокое давление в системе	f	112
416	Загрязнение масла воздухом	f	112
417	Перегрев рабочей жидкости	f	112
418	Эрозия поверхностей деталей и шум	t	113
419	Повышение КПД системы	f	113
420	Уменьшение износа деталей	f	113
421	Никаких последствий не вызывает	f	113
422	Увеличивает потери давления и нагрев	t	114
423	Улучшает смазывание	f	114
424	Не влияет на работу	f	114
425	Уменьшает утечки через уплотнения	f	114
426	Tandem (P соединён с T в нейтрали)	t	115
427	Closed center (все порты закрыты)	f	115
428	Float centre (плавное перемещение)	f	115
429	Регулируемый	f	115
430	Рабочая среда для передачи энергии в гидросистеме	t	116
431	Охлаждающая жидкость	f	116
432	Топливо для двигателя	f	116
433	Смазка для подшипников	f	116
434	Минеральное гидравлическое масло	t	117
435	Моторное масло	f	117
436	Трансмиссионное масло	f	117
437	Синтетическое моторное масло	f	117
438	Низкая вязкость при любой температуре	f	118
439	Стабильность вязкости в рабочем диапазоне температур	t	118
440	Низкая цена	f	118
441	Приятный запах	f	118
442	Жидкость после исполнительного органа возвращается в бак	t	119
443	Жидкость циркулирует по замкнутому кругу	f	119
444	Схема не имеет предохранительных клапанов	f	119
445	Схема имеет сливную линию	f	119
446	Жидкость постоянно циркулирует от насоса к гидромотору и обратно	t	120
447	Наличие большого бака	f	120
448	Слив жидкости в атмосферу	f	120
449	Низкое рабочее давление	f	120
450	Огнестойкая гидравлическая жидкость	t	121
451	Высоковязкая жидкость	f	121
452	Биоразлагаемая жидкость	f	121
453	Жидкость с присадками	f	121
454	ISO 16/13/10	f	122
455	ISO 18/15/12	f	122
456	ISO 14/11/8	t	122
457	ISO 20/18/15	f	122
458	Разрывом шлангов и повреждением компонентов	t	123
459	Увеличением КПД	f	123
460	Ускорением работы механизмов	f	123
461	Снижением температуры масла	f	123
462	Для предотвращения гидроудара при разрыве шланга	t	124
463	Для соединения двух рукавов	f	124
464	Для крепления рукава к раме	f	124
465	Для изменения диаметра	f	124
466	Нагрузка, направленная вдоль оси вала	t	125
467	Радиальная нагрузка	f	125
468	Крутящий момент	f	125
469	Частота вращения	f	125
470	Шестерённый насос	t	126
471	Пластинчатый насос	f	126
472	Аксиально-поршневой насос	f	126
473	Винтовой насос	f	126
474	Резкое повышение давления при внезапной остановке потока жидкости	t	127
475	Удар детали о корпус	f	127
476	Падение давления в системе	f	127
477	Разрыв вала насоса	f	127
478	Выше +40°C	f	128
479	Выше +60°C	f	128
480	Выше +80°C	t	128
481	Выше +100°C	f	128
482	Раз в год	f	129
483	По результатам анализа состояния масла	t	129
484	Раз в 5 лет	f	129
485	Никогда не менять	f	129
486	Угол конуса уплотнения	t	130
487	Диаметр фитинга	f	130
488	Рабочее давление	f	130
489	Температуру эксплуатации	f	130
490	Разрушение рукава из-за превышения давления	t	131
491	Нормальный износ рукава	f	131
492	Разъём рукава для обслуживания	f	131
493	Срабатывание предохранительного клапана	f	131
494	Манометром	t	132
495	Термометром	f	132
496	Расходомером	f	132
497	Секундомером	f	132
498	Резервуар для хранения рабочей жидкости	t	133
499	Устройство для нагрева масла	f	133
500	Инструмент для измерения объёма	f	133
501	Фильтр тонкой очистки	f	133
502	1-2 минутной производительности насоса	t	134
503	Как можно меньше	f	134
504	Чем больше, тем лучше	f	134
505	5-10 литров	f	134
\.


--
-- Data for Name: Available tests; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."Available tests" (id, name, max_attempts) FROM stdin;
2	Кандидат	3
1	Админ	3
\.


--
-- Data for Name: Available tests_tests; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."Available tests_tests" (id, studenttype_id, test_id) FROM stdin;
9	1	14
10	1	15
11	1	16
\.


--
-- Data for Name: Question; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."Question" (id, text, image, test_id) FROM stdin;
87	Что изображено на картинке ?	question_images/Part_scheme.png	14
88	Что такое гидростатика?		16
89	Какая жидкость считается идеальной в гидравлике?		16
90	Закон Паскаля гласит:		16
91	По какой формуле рассчитывается гидростатическое давление?		16
92	Что характеризует кинематическая вязкость?		16
93	Какой насос относится к объёмным?		16
94	Какое основное преимущество аксиально-поршневого насоса?		16
95	Что такое рабочий объём гидронасоса?		16
96	Какая формула используется для расчёта подачи насоса?		16
97	Что такое гидромотор?		16
98	Чем отличается гидромотор от насоса по конструкции?		16
99	Какой тип гидромотора имеет наибольший пусковой момент?		16
100	Единица измерения давления в системе СИ:		16
101	Сколько бар в 1 МПа?		16
102	Для чего служит предохранительный клапан?		16
103	Что такое гидравлический распределитель?		16
104	Что означает обозначение 4/3 для гидрораспределителя?		16
54	Что измеряет амперметр?		14
55	Какое устройство преобразует электрическую энергию в механическую?		14
56	Как изменяется общее сопротивление при последовательном соединении?	series.png	14
57	Как изменяется ток в параллельной цепи?	parallel.png	14
58	Единица измерения сопротивления:		14
59	Машина должна быть чистой, трейлеры должны быть освобождены от грузов, прежде чем машина будет доставлена на участок ТО для проведения техобслуживания или ремонта ?		15
60	Парковочный тормоз приводится в действие ?		15
61	Заправка гидравлического масла производится: 		15
62	Система забора воздуха должна тщательно осматриваться и проверяться ежедневно, т.к.:		15
63	Система забора воздуха должна тщательно осматриваться и проверяться ежедневно, т.к.:		15
64	Каким способом производится заправка ПСМ моторным маслом?		15
65	Уровень гидравлического масла визуально можно оценить:		15
66	Тормозная система на ПСМ является:		15
67	Для корректной работы и обмена данными между логическими контроллерами, сопротивление на линии цифровой шины обмена данными CAN должно составлять:		15
68	Работа оборудования трейлера ПСМ для доставки бетонной смеси активируется:		15
69	После загрузки бетоносмесителя необходимо:		15
70	Аварийный режим активируется:		15
71	С какой периодичностью необходимо производить замену масла в корпусе гипоидной передачи и бортовых редукторах ведущих мостов:		15
72	С какой периодичностью производиться регулировка зазора клапанов ДВС:		15
73	На основании какой информации производится планирование сервисных работ:		15
74	ПСМ можно буксировать на скорости:		15
75	Момент затяжки колесных гаек составляет:		15
76	С какой периодичностью необходимо проводить замену фильтра осушителя пневматической системы:		15
77	Какую гидравлическую жидкость необходимо использовать при доливке во время эксплуатации и замене при проведении ТО:		15
78	Максимальное давление в гидростатическом приводе ПСМ может достигать:		15
79	Какое напряжение бортовой сети машины:		15
80	Уровень охлаждающей жидкости радиатора проверяется:		15
81	Машинист обязан проводить осмотр машины:		15
82	ПСМ приводится в движение с помощью гидравлического насоса и...:		15
83	Насос раздачи топлива на ПСМ доставки ГСМ работает с помощью:		15
84	Фары головного освещения, освещения рабочей зоны включаются и выключаются:		15
85	В случае аварийной ситуации, когда двигатель не заводится, машину можно отбуксировать:		15
86	Движение вперед и назад включается		15
105	Для чего предназначен обратный клапан?		16
106	Какое требование предъявляется к гидравлическим рукавам высокого давления (РВД)?		16
107	Какой слой в РВД отвечает за герметичность?		16
108	Что указывается в маркировке РВД?		16
109	Какой тип фильтрации считается наиболее эффективным?		16
110	Что такое дроссель в гидравлике?		16
111	Для чего нужен гидроаккумулятор?		16
112	Что такое кавитация в гидросистеме?		16
113	Какие последствия вызывает кавитация?		16
114	Как влияет повышенная вязкость масла на работу гидросистемы?		16
115	Как обозначается золотник с открытым центром?		16
116	Что такое гидравлическая жидкость?		16
117	Какое масло чаще всего используется в промышленных гидросистемах?		16
118	Какое требование к гидравлическому маслу является главным?		16
119	Что означает понятие «открытая гидравлическая схема»?		16
120	Что характерно для закрытой гидравлической схемы?		16
121	Что такое гидравлическая жидкость HFD?		16
122	Какой класс чистоты жидкости является допустимым для высокоточных гидросистем?		16
123	Чем опасно превышение допустимого давления в гидросистеме?		16
124	Для чего служит разрывная муфта на РВД?		16
125	Что означает осевая нагрузка на гидромотор?		16
126	Какой тип насоса используется в системе рулевого управления автомобиля?		16
127	Что такое гидравлический удар?		16
128	Какое значение температуры масла в гидросистеме считается критическим?		16
129	Как часто рекомендуется менять гидравлическое масло в промышленных системах?		16
130	Что обозначает маркировка фитинга DIN 24°?		16
131	Что такое гидравлический разрыв рукава?		16
132	Каким прибором измеряют давление в гидросистеме?		16
133	Что такое гидравлическая ёмкость (бак)?		16
134	Какой объем гидробака рекомендуется для открытой гидравлической системы?		16
\.


--
-- Data for Name: UserAnswer; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."UserAnswer" (id, is_correct, question_id, selected_option_id, user_id, attempt_id) FROM stdin;
433	f	87	314	1	92
434	t	55	216	1	93
435	t	56	219	1	93
436	t	57	223	1	93
437	t	54	212	1	93
438	t	87	316	1	93
439	t	58	228	1	93
440	f	55	214	5	94
441	f	54	213	5	94
442	t	87	316	5	94
443	t	57	223	5	94
444	f	56	221	5	94
445	t	58	228	5	94
446	t	103	378	1	97
447	t	127	474	1	97
448	f	90	328	1	97
449	f	124	465	1	97
450	f	98	359	1	97
451	f	93	340	1	97
452	f	99	365	1	97
453	t	116	430	1	97
454	f	107	394	1	97
455	f	131	491	1	97
456	f	101	373	1	97
457	t	89	322	1	97
458	f	97	356	1	97
459	f	133	499	1	97
460	f	111	411	1	97
461	f	113	419	1	97
462	f	118	440	1	97
463	t	129	483	1	97
464	t	119	442	1	97
465	t	114	422	1	97
466	t	100	367	1	97
467	f	120	449	1	97
468	f	105	389	1	97
469	f	102	374	1	97
470	f	117	437	1	97
471	f	106	392	1	97
472	f	94	344	1	97
473	f	91	332	1	97
474	f	121	451	1	97
475	f	109	402	1	97
476	f	125	467	1	97
477	t	95	346	1	97
478	f	123	459	1	97
479	f	122	457	1	97
480	t	132	494	1	97
481	t	92	334	1	97
482	f	128	479	1	97
483	f	104	384	1	97
484	f	110	407	1	97
485	t	108	398	1	97
486	f	88	320	1	97
487	t	130	486	1	97
488	t	96	350	1	97
489	f	134	503	1	97
490	t	126	470	1	97
491	t	115	426	1	97
492	f	112	415	1	97
\.


--
-- Data for Name: UserTestResult; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public."UserTestResult" (id, score, total_questions, correct_answers, completed_at, attempt_id, user_id) FROM stdin;
83	100	6	6	2026-06-11 13:51:49.879239+07	93	1
84	50	6	3	2026-06-11 13:56:54.306185+07	94	5
85	34.04255319148936	47	16	2026-06-16 08:30:51.184304+07	97	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Доступные тесты	6	add_studenttype
22	Can change Доступные тесты	6	change_studenttype
23	Can delete Доступные тесты	6	delete_studenttype
24	Can view Доступные тесты	6	view_studenttype
25	Can add Студента	7	add_student
26	Can change Студента	7	change_student
27	Can delete Студента	7	delete_student
28	Can view Студента	7	view_student
29	Can add Вопрос	8	add_question
30	Can change Вопрос	8	change_question
31	Can delete Вопрос	8	delete_question
32	Can view Вопрос	8	view_question
33	Can add Тест	9	add_test
34	Can change Тест	9	change_test
35	Can delete Тест	9	delete_test
36	Can view Тест	9	view_test
37	Can add Категорию	10	add_testcategories
38	Can change Категорию	10	change_testcategories
39	Can delete Категорию	10	delete_testcategories
40	Can view Категорию	10	view_testcategories
41	Can add user test attempt	11	add_usertestattempt
42	Can change user test attempt	11	change_usertestattempt
43	Can delete user test attempt	11	delete_usertestattempt
44	Can view user test attempt	11	view_usertestattempt
45	Can add Результаты теста	12	add_usertestresult
46	Can change Результаты теста	12	change_usertestresult
47	Can delete Результаты теста	12	delete_usertestresult
48	Can view Результаты теста	12	view_usertestresult
49	Can add Опции ответа	13	add_answeroption
50	Can change Опции ответа	13	change_answeroption
51	Can delete Опции ответа	13	delete_answeroption
52	Can view Опции ответа	13	view_answeroption
53	Can add Ответ пользователя	14	add_useranswer
54	Can change Ответ пользователя	14	change_useranswer
55	Can delete Ответ пользователя	14	delete_useranswer
56	Can view Ответ пользователя	14	view_useranswer
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-16 08:23:59.11696+07	1	Электрика	1	[{"added": {}}]	9	1
2	2026-04-16 08:27:39.672318+07	1	Электрика	2	[]	9	1
3	2026-04-16 08:43:20.251465+07	1	Админ	1	[{"added": {}}]	6	1
4	2026-04-16 08:43:35.191785+07	1	root	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u0435", "\\u0423\\u0447\\u0430\\u0441\\u0442\\u043e\\u043a", "\\u0414\\u043e\\u043b\\u0436\\u043d\\u043e\\u0441\\u0442\\u044c", "\\u041e\\u0442\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e", "\\u0422\\u0438\\u043f \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u0430"]}}]	7	1
5	2026-04-16 09:43:13.347758+07	1	Админ	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
6	2026-04-16 09:44:05.477387+07	1	Админ	2	[]	6	1
7	2026-04-16 09:46:52.070136+07	1	Админ	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
8	2026-04-16 09:47:09.771395+07	5	root | 40.0	3		12	1
9	2026-04-16 09:47:12.888054+07	4	root | 0.0	3		12	1
10	2026-04-16 09:47:15.730709+07	3	root | 80.0	3		12	1
11	2026-04-16 09:48:23.96666+07	10	root -> Единица измерения сопротивления:-> Ампер	3		14	1
12	2026-04-16 09:48:26.664123+07	9	root -> Как изменяется ток в параллельной цепи?-> Увеличивается в 2 раза	3		14	1
13	2026-04-16 09:48:29.337293+07	8	root -> Как изменяется общее сопротивление при последовательном соединении?-> Складывается	3		14	1
14	2026-04-16 09:48:37.999862+07	7	root -> Какое устройство преобразует электрическую энергию в механическую?-> Резистор	3		14	1
15	2026-04-16 09:48:37.999862+07	6	root -> Что измеряет амперметр?-> Силу тока	3		14	1
16	2026-04-16 09:48:37.999862+07	5	root -> Единица измерения сопротивления:-> Ом	3		14	1
17	2026-04-16 09:48:37.999862+07	4	root -> Как изменяется ток в параллельной цепи?-> Одинаков во всех ветвях	3		14	1
18	2026-04-16 09:48:37.999862+07	3	root -> Как изменяется общее сопротивление при последовательном соединении?-> Складывается	3		14	1
19	2026-04-16 09:48:37.999862+07	2	root -> Какое устройство преобразует электрическую энергию в механическую?-> Электродвигатель	3		14	1
20	2026-04-16 09:48:37.999862+07	1	root -> Что измеряет амперметр?-> Силу тока	3		14	1
21	2026-04-16 10:11:09.341736+07	4	root | Тест по электрике | False	3		11	1
22	2026-04-16 10:11:09.341736+07	3	root | Тест по электрике | True	3		11	1
23	2026-04-16 10:11:09.341736+07	2	root | Тест по электрике | True	3		11	1
24	2026-04-16 10:11:09.341736+07	1	root | Электрика | True	3		11	1
25	2026-04-16 10:30:49.165518+07	1	Админ	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
26	2026-04-16 11:54:02.414086+07	6	Что изображено на картинке ?	1	[{"added": {}}]	8	1
27	2026-04-16 11:54:23.782483+07	21	Предохранитель	1	[{"added": {}}]	13	1
28	2026-04-16 11:54:37.520786+07	22	Соленоид	1	[{"added": {}}]	13	1
29	2026-04-16 11:54:54.056563+07	23	Выключатель	1	[{"added": {}}]	13	1
30	2026-04-16 11:55:03.105736+07	24	Резистор	1	[{"added": {}}]	13	1
31	2026-05-13 14:08:13.987505+07	2	Repair	2	[]	7	1
32	2026-05-13 14:08:43.373831+07	2	Кандидат	1	[{"added": {}}]	6	1
33	2026-05-13 14:08:52.587338+07	2	Repair	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u0430"]}}]	7	1
34	2026-05-13 14:08:55.92763+07	2	Repair	2	[]	7	1
35	2026-05-14 10:34:03.958782+07	3	Fedor	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u0430"]}}]	7	1
36	2026-05-14 14:03:10.829885+07	4	AlexUser ====>>> Александр Фёдоров Андреевич	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u0430"]}}]	7	1
37	2026-05-14 14:43:59.951408+07	2	Кандидат	2	[{"changed": {"fields": ["Tests"]}}]	6	1
38	2026-05-18 08:47:58.119431+07	3	Тестовый тест с очень длинным очень длинным названием  2 категории	1	[{"added": {}}]	9	1
39	2026-05-18 08:48:06.608129+07	1	Админ	2	[{"changed": {"fields": ["Tests"]}}]	6	1
40	2026-05-18 08:49:48.989021+07	3	Тестовый тест с очень длинным очень длинным названием  2 категории	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
41	2026-05-19 08:08:44.295836+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
42	2026-05-19 08:34:11.142847+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
43	2026-05-19 08:44:43.048073+07	2	Кандидат	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
44	2026-05-19 08:44:54.174391+07	26	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | False	3		11	1
45	2026-05-19 08:48:57.843585+07	2	Кандидат	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
46	2026-05-19 11:07:28.575529+07	2	Кандидат	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
47	2026-05-19 11:07:47.558808+07	30	root ====>>>   root | Тест по электрике | True	3		11	1
48	2026-05-19 11:07:47.558808+07	29	root ====>>>   root | Тест по электрике | True	3		11	1
49	2026-05-19 11:07:47.558808+07	28	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | False	3		11	1
50	2026-05-19 11:07:47.558808+07	27	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | False	3		11	1
51	2026-05-19 11:07:47.558808+07	25	root ====>>>   root | Тест по электрике | True	3		11	1
52	2026-05-19 11:07:47.558808+07	24	root ====>>>   root | Электрика | True	3		11	1
53	2026-05-19 11:07:47.558808+07	23	root ====>>>   root | Тест по электрике | False	3		11	1
54	2026-05-19 11:07:47.558808+07	22	root ====>>>   root | Тестовый тест с очень длинным очень длинным названием  2 категории | True	3		11	1
55	2026-05-19 11:07:47.558808+07	21	root ====>>>   root | Тест по электрике | True	3		11	1
56	2026-05-19 11:07:47.558808+07	20	root ====>>>   root | Тест по электрике | True	3		11	1
57	2026-05-19 11:07:47.558808+07	19	root ====>>>   root | Электрика | True	3		11	1
58	2026-05-19 11:07:47.558808+07	18	root ====>>>   root | Тест по электрике | False	3		11	1
59	2026-05-19 11:07:47.558808+07	17	root ====>>>   root | Электрика | True	3		11	1
60	2026-05-19 11:07:47.558808+07	16	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
61	2026-05-19 11:07:47.558808+07	15	root ====>>>   root | Тест по электрике | True	3		11	1
62	2026-05-19 11:07:47.558808+07	14	root ====>>>   root | Электрика | True	3		11	1
63	2026-05-19 11:07:47.558808+07	13	root ====>>>   root | Тест по электрике | False	3		11	1
64	2026-05-19 11:07:47.558808+07	12	AlexUser ====>>> Александр Фёдоров Андреевич | Электрика | True	3		11	1
65	2026-05-19 11:07:47.558808+07	11	Repair ====>>> Владимир ноутбуков Компьютерович | Электрика | True	3		11	1
66	2026-05-19 11:07:47.558808+07	10	root ====>>>   root | Тест по электрике | True	3		11	1
67	2026-05-19 11:07:47.558808+07	9	root ====>>>   root | Тест по электрике | True	3		11	1
68	2026-05-19 11:07:47.558808+07	8	root ====>>>   root | Тест по электрике | True	3		11	1
69	2026-05-19 11:07:47.558808+07	7	root ====>>>   root | Тест по электрике | False	3		11	1
70	2026-05-19 11:07:47.558808+07	6	root ====>>>   root | Тест по электрике | True	3		11	1
71	2026-05-19 11:07:47.558808+07	5	root ====>>>   root | Тест по электрике | True	3		11	1
72	2026-05-19 12:24:47.240947+07	33	root ====>>>   root | Тест по электрике | True	3		11	1
73	2026-05-19 12:24:47.240947+07	32	root ====>>>   root | Тест по электрике | True	3		11	1
74	2026-05-19 12:24:47.242298+07	31	root ====>>>   root | Тест по электрике | True	3		11	1
75	2026-05-19 13:35:04.850753+07	34	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
76	2026-05-19 14:01:43.001147+07	37	root ====>>>   root | Тест по электрике | True	3		11	1
77	2026-05-19 14:01:43.001147+07	36	root ====>>>   root | Тест по электрике | True	3		11	1
78	2026-05-19 14:01:43.001147+07	35	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
79	2026-05-19 15:15:12.29608+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
80	2026-05-19 15:51:38.571083+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
81	2026-05-19 15:51:58.982507+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
82	2026-05-19 15:52:11.955999+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
83	2026-05-19 15:52:21.047554+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
84	2026-05-19 15:52:31.220909+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
85	2026-05-20 08:50:37.589978+07	43	root ====>>>   root | Тест по электрике | True	3		11	1
86	2026-05-20 08:50:37.589978+07	42	root ====>>>   root | Тест по электрике | True	3		11	1
87	2026-05-20 08:50:37.589978+07	41	root ====>>>   root | Тест по электрике | True	3		11	1
88	2026-05-20 08:50:37.589978+07	40	root ====>>>   root | Тест по электрике | True	3		11	1
89	2026-05-20 08:50:37.589978+07	39	root ====>>>   root | Тест по электрике | True	3		11	1
90	2026-05-20 08:50:37.589978+07	38	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
91	2026-05-20 09:20:51.048973+07	2	Кандидат	2	[{"changed": {"fields": ["\\u041c\\u0430\\u043a\\u0441\\u0438\\u043c\\u0443\\u043c \\u043f\\u043e\\u043f\\u044b\\u0442\\u043e\\u043a \\u043d\\u0430 \\u0442\\u0435\\u0441\\u0442"]}}]	6	1
92	2026-05-20 10:34:16.582907+07	45	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
93	2026-05-20 10:34:16.582907+07	44	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
94	2026-05-20 10:36:44.424904+07	3	Тестовый тест с очень длинным очень длинным названием  2 категории	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
95	2026-05-20 10:36:48.362799+07	2	Тест по электрике	2	[]	9	1
96	2026-05-20 10:36:52.650758+07	1	Электрика	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
97	2026-05-21 08:07:06.237881+07	4	Как изменяется ток в параллельной цепи?	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	8	1
98	2026-05-21 08:07:17.61873+07	3	Как изменяется общее сопротивление при последовательном соединении?	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	8	1
99	2026-05-26 08:03:14.033544+07	2	Тест по электрике	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
100	2026-05-26 09:30:34.547961+07	63	root ====>>>   root | Тест по электрике | True	3		11	1
101	2026-05-26 09:30:34.547961+07	62	root ====>>>   root | Тест по электрике | False	3		11	1
102	2026-05-26 09:30:34.547961+07	61	root ====>>>   root | Тест по электрике | True	3		11	1
103	2026-05-26 09:30:34.547961+07	60	root ====>>>   root | Тест по электрике | True	3		11	1
104	2026-05-26 09:30:34.547961+07	59	root ====>>>   root | Тест по электрике | True	3		11	1
105	2026-05-26 09:30:34.547961+07	58	root ====>>>   root | Тест по электрике | False	3		11	1
106	2026-05-26 09:30:34.547961+07	57	root ====>>>   root | Тест по электрике | True	3		11	1
107	2026-05-26 09:30:34.547961+07	56	root ====>>>   root | Тест по электрике | True	3		11	1
108	2026-05-26 09:30:34.548568+07	55	root ====>>>   root | Электрика | True	3		11	1
109	2026-05-26 09:30:34.548568+07	54	root ====>>>   root | Тест по электрике | True	3		11	1
110	2026-05-26 09:30:34.548568+07	53	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
111	2026-05-26 09:30:34.548568+07	52	root ====>>>   root | Тест по электрике | True	3		11	1
112	2026-05-26 09:30:34.548568+07	51	root ====>>>   root | Тест по электрике | True	3		11	1
113	2026-05-26 09:30:34.548568+07	50	root ====>>>   root | Тест по электрике | True	3		11	1
114	2026-05-26 09:30:34.548568+07	49	Fedor ====>>> Frdor Save save | Тест по электрике | True	3		11	1
115	2026-05-26 09:30:34.548568+07	48	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
116	2026-05-26 09:30:34.548568+07	47	root ====>>>   root | Тестовый тест с очень длинным очень длинным названием  2 категории | True	3		11	1
117	2026-05-26 09:30:34.548568+07	46	root ====>>>   root | Тест по электрике | True	3		11	1
118	2026-05-26 10:48:57.322629+07	67	root ====>>>   root | Тест по электрике | True	3		11	1
119	2026-05-26 10:48:57.322629+07	66	root ====>>>   root | Тест по электрике | True	3		11	1
120	2026-05-26 10:48:57.322629+07	65	root ====>>>   root | Тест по электрике | True	3		11	1
121	2026-05-26 10:48:57.322629+07	64	root ====>>>   root | Тест по электрике | False	3		11	1
122	2026-05-26 11:00:47.640405+07	71	root ====>>>   root | Тест по электрике | True	3		11	1
123	2026-05-26 11:00:47.640405+07	70	root ====>>>   root | Тест по электрике | True	3		11	1
124	2026-05-26 11:00:47.640405+07	69	root ====>>>   root | Тест по электрике | True	3		11	1
125	2026-05-26 11:00:47.640405+07	68	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
126	2026-05-27 09:45:18.730092+07	77	root ====>>>   root | Тест по электрике | True	3		11	1
127	2026-05-27 09:45:18.730092+07	76	root ====>>>   root | Электрика | True	3		11	1
128	2026-05-27 09:45:18.730092+07	75	root ====>>>   root | Тест по электрике | True	3		11	1
129	2026-05-27 09:45:18.730092+07	74	root ====>>>   root | Тест по электрике | True	3		11	1
130	2026-05-27 09:45:18.730092+07	72	root ====>>>   root | Тест по электрике | True	3		11	1
131	2026-05-27 09:45:18.730092+07	73	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
132	2026-05-28 08:38:45.440597+07	83	root ====>>>   root | Тестовый тест с очень длинным очень длинным названием  2 категории | True	3		11	1
133	2026-05-28 08:38:45.440597+07	82	root ====>>>   root | Электрика | True	3		11	1
134	2026-05-28 08:38:45.440597+07	81	root ====>>>   root | Тестовый тест с очень длинным очень длинным названием  2 категории | True	3		11	1
135	2026-05-28 08:38:45.440597+07	80	root ====>>>   root | Тестовый тест с очень длинным очень длинным названием  2 категории | True	3		11	1
136	2026-05-28 08:38:45.440597+07	79	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
137	2026-05-28 08:38:45.440597+07	78	root ====>>>   root | Тест по электрике | True	3		11	1
138	2026-06-02 08:20:36.565594+07	11	kkkkk	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
139	2026-06-02 08:29:05.704684+07	1	Админ	2	[{"changed": {"fields": ["Tests"]}}]	6	1
140	2026-06-02 08:43:01.447388+07	11	kkkkk	3		9	1
141	2026-06-02 08:43:01.447388+07	10	kkkk	3		9	1
142	2026-06-02 08:43:01.447388+07	9	Тест по электрике	3		9	1
143	2026-06-02 08:43:01.447388+07	8	Тест по электрике	3		9	1
144	2026-06-02 08:43:01.447388+07	7	Тест по электрике	3		9	1
145	2026-06-02 08:43:01.447388+07	6	Тест по электрике	3		9	1
146	2026-06-02 08:43:01.447388+07	5	Тест по электрике	3		9	1
147	2026-06-02 08:43:01.447388+07	4	Тест по электрике	3		9	1
148	2026-06-02 08:43:01.447388+07	3	Тестовый тест с очень длинным очень длинным названием  2 категории	3		9	1
149	2026-06-02 08:52:11.118547+07	2	Тест по электрике	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
150	2026-06-02 08:52:45.612614+07	84	AlexUser ====>>> Александр Фёдоров Андреевич | Тест по электрике | True	3		11	1
151	2026-06-02 09:05:03.696635+07	2	Тест по электрике	3		9	1
152	2026-06-02 09:05:03.696635+07	1	Электрика	3		9	1
153	2026-06-02 09:05:53.211033+07	1	Админ	2	[{"changed": {"fields": ["Tests"]}}]	6	1
154	2026-06-02 09:06:03.507509+07	12	Электрика	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
155	2026-06-02 09:06:08.034277+07	13	Вводная программа по эксплуатации и обслуживанию подземной свмоходной техники Хенкон	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
156	2026-06-02 09:06:41.068498+07	12	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
157	2026-06-02 09:06:47.621716+07	13	Вводная программа по эксплуатации и обслуживанию подземной свмоходной техники Хенкон	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
158	2026-06-02 13:54:35.370518+07	13	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	2	[{"changed": {"fields": ["Title"]}}]	9	1
159	2026-06-03 08:50:10.745244+07	13	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	3		9	1
160	2026-06-03 08:50:10.745244+07	12	Электрика	3		9	1
161	2026-06-03 08:50:53.745323+07	14	Электрика	2	[{"changed": {"fields": ["Time limit", "\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
162	2026-06-03 08:51:07.693746+07	15	Вводная программа по эксплуатации и обслуживанию подземной свмоходной техники Хенкон	2	[{"changed": {"fields": ["Time limit", "\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
163	2026-06-03 08:51:29.069924+07	1	Админ	2	[{"changed": {"fields": ["Tests"]}}]	6	1
164	2026-06-03 08:52:42.343125+07	15	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	2	[{"changed": {"fields": ["Title"]}}]	9	1
165	2026-06-11 11:20:25.397988+07	91	root ====>>>   root | Электрика | True	3		11	1
166	2026-06-11 11:20:25.397988+07	90	root ====>>>   root | Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон | True	3		11	1
167	2026-06-11 11:20:25.397988+07	89	root ====>>>   root | Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон | True	3		11	1
168	2026-06-11 11:20:25.397988+07	88	root ====>>>   root | Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон | True	3		11	1
169	2026-06-11 11:22:53.121493+07	87	Что изображено на картинке ?	1	[{"added": {}}]	8	1
170	2026-06-11 11:23:21.05799+07	314	Катушка	1	[{"added": {}}]	13	1
171	2026-06-11 11:23:29.632672+07	315	Соленоид	1	[{"added": {}}]	13	1
172	2026-06-11 11:23:35.404638+07	316	Реле	1	[{"added": {}}]	13	1
173	2026-06-11 11:23:46.378142+07	317	Предохранитель	1	[{"added": {}}]	13	1
174	2026-06-11 13:56:05.757918+07	5	IvanChief ====>>> Иван Иванов Юрьевич	2	[{"changed": {"fields": ["\\u0422\\u0438\\u043f \\u0441\\u0442\\u0443\\u0434\\u0435\\u043d\\u0442\\u0430"]}}]	7	1
175	2026-06-11 13:56:25.82187+07	5	IvanChief ====>>> Иван Иванов Юрьевич	2	[]	7	1
176	2026-06-11 14:18:09.615292+07	5	IvanChief ====>>> Иван Иванов Юрьевич	2	[{"changed": {"fields": ["Staff status"]}}]	7	1
177	2026-06-15 09:06:40.077074+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
178	2026-06-15 09:41:12.303206+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
179	2026-06-15 09:42:20.958361+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
180	2026-06-15 11:43:54.857083+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
181	2026-06-15 11:44:01.990218+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
182	2026-06-15 13:23:16.027742+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
183	2026-06-15 13:26:06.567313+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
184	2026-06-15 13:27:09.331943+07	15	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
185	2026-06-15 13:56:57.742011+07	15	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
186	2026-06-15 13:57:06.117839+07	15	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
187	2026-06-16 08:04:03.201833+07	14	Электрика	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
188	2026-06-16 08:19:39.431734+07	1	Админ	2	[{"changed": {"fields": ["Tests"]}}]	6	1
189	2026-06-16 08:20:08.823656+07	16	Основы гидравлики для гидравликов	2	[{"changed": {"fields": ["Time limit"]}}]	9	1
190	2026-06-16 08:20:20.330117+07	1	Админ	2	[]	6	1
191	2026-06-16 08:27:52.499113+07	16	Основы гидравлики для гидравликов	2	[{"changed": {"fields": ["\\u0418\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435"]}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	main	studenttype
7	main	student
8	gtests	question
9	gtests	test
10	gtests	testcategories
11	gtests	usertestattempt
12	gtests	usertestresult
13	gtests	answeroption
14	gtests	useranswer
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	gtests	0001_initial	2026-04-16 08:18:39.354592+07
2	contenttypes	0001_initial	2026-04-16 08:18:39.364559+07
3	contenttypes	0002_remove_content_type_name	2026-04-16 08:18:39.372559+07
4	auth	0001_initial	2026-04-16 08:18:39.404611+07
5	auth	0002_alter_permission_name_max_length	2026-04-16 08:18:39.407633+07
6	auth	0003_alter_user_email_max_length	2026-04-16 08:18:39.410627+07
7	auth	0004_alter_user_username_opts	2026-04-16 08:18:39.413597+07
8	auth	0005_alter_user_last_login_null	2026-04-16 08:18:39.418626+07
9	auth	0006_require_contenttypes_0002	2026-04-16 08:18:39.419629+07
10	auth	0007_alter_validators_add_error_messages	2026-04-16 08:18:39.42463+07
11	auth	0008_alter_user_username_max_length	2026-04-16 08:18:39.426643+07
12	auth	0009_alter_user_last_name_max_length	2026-04-16 08:18:39.430597+07
13	auth	0010_alter_group_name_max_length	2026-04-16 08:18:39.436633+07
14	auth	0011_update_proxy_permissions	2026-04-16 08:18:39.44163+07
15	auth	0012_alter_user_first_name_max_length	2026-04-16 08:18:39.445632+07
16	main	0001_initial	2026-04-16 08:18:39.497659+07
17	admin	0001_initial	2026-04-16 08:18:39.519099+07
18	admin	0002_logentry_remove_auto_add	2026-04-16 08:18:39.526125+07
19	admin	0003_logentry_add_action_flag_choices	2026-04-16 08:18:39.531102+07
20	gtests	0002_initial	2026-04-16 08:18:39.588123+07
21	sessions	0001_initial	2026-04-16 08:18:39.598126+07
22	gtests	0003_alter_usertestattempt_unique_together_and_more	2026-04-16 09:42:00.271566+07
23	main	0002_studenttype_max_attempts	2026-04-16 09:42:00.314546+07
24	gtests	0004_usertestattempt_is_active	2026-04-16 10:04:34.335797+07
25	gtests	0005_delete_testcategories_alter_usertestattempt_options	2026-04-16 10:18:32.965218+07
28	gtests	0006_alter_answeroption_options_and_more	2026-05-19 13:33:50.736104+07
29	main	0003_alter_studenttype_options	2026-06-15 08:55:52.313261+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
bclp4itfkxh4vljryc4tx31sit6bhziv	.eJxVjEEOwiAQRe_C2pAChTIu3XsGwsCMVA0kpV0Z765NutDtf-_9lwhxW0vYOi1hzuIslDj9bhjTg-oO8j3WW5Op1XWZUe6KPGiX15bpeTncv4MSe_nWdgSGTBZIDVOyxgIT8KBc1kYbG9WYHBrwE3uHqBE4sTMWHXgm7ZN4fwDVvDfO:1wZIdf:Ln6ppRQ_H2dblmLSKkGjSidH-5kCK4W0c9nnnwMXBmQ	2026-06-30 08:30:51.217178+07
\.


--
-- Data for Name: gtests_usertestattempt; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.gtests_usertestattempt (id, started_at, completed, test_id, user_id, is_active) FROM stdin;
92	2026-06-11 11:24:02.241151+07	f	14	1	t
93	2026-06-11 13:51:17.83898+07	t	14	1	t
94	2026-06-11 13:56:45.052737+07	t	14	5	t
95	2026-06-11 14:14:50.379605+07	f	14	5	t
96	2026-06-15 09:58:11.564655+07	f	15	1	t
97	2026-06-16 08:29:45.190947+07	t	16	1	t
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.student (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, enterprise, plot, function, surname, student_type_id) FROM stdin;
2	pbkdf2_sha256$1000000$0esEnihObe4M1lrggyGrBE$07d9WoRNrWXjKU0PnkiZD59UyXx52BSdSrhdrnuuMd8=	2026-05-13 14:25:40.58771+07	f	Repair	Владимир	ноутбуков	JJJdh@mail.ru	f	t	2026-05-13 08:16:00+07	КУча	КУча	КУча	Компьютерович	2
5	pbkdf2_sha256$1000000$toIlEYopiHaXrKNZbxAYvt$KzTsy2LzEYPNQ+ESvRgjenAq0EzqXBQuzdBF8JIJJV4=	2026-06-11 14:18:30.309481+07	f	IvanChief	Иван	Иванов	I.ivanov@hencon.ru	t	t	2026-06-11 13:55:33+07	Геккон	ДТОиР	Начальник департамента	Юрьевич	1
1	pbkdf2_sha256$1000000$d7YfOQ8zYQbd6t7KrhVQK1$6nD0vfD9wIRFMbaKmpQq5ZIj1iWhQdiz2L38KtUD1zw=	2026-06-16 08:28:01.822048+07	t	root				t	t	2026-04-16 08:19:03+07	root	root	root	root	1
6	pbkdf2_sha256$1000000$vKZNZOVDdTN0a63XuYrrIA$01Qxo4isFhAgk1menplDPFnUi/7iYPpmHSJSigPJTp4=	\N	f	hhhhh	hhhhh	hhhhhh	hhhhh@mail.ru	f	t	2026-06-15 08:41:03.394401+07	hhhhhh	hhhhhh	hhhhh	hhhhh	\N
3	pbkdf2_sha256$1000000$kkjBCC7nfMPNAlb34LvzV7$q8b35EFRxdSvqmy7rATnJW/nKp7FqsTUOLsWAyMBjqM=	2026-05-20 11:12:36.74728+07	f	Fedor	Frdor	Save	henc@mail.ru	f	t	2026-05-14 09:11:46+07	henc	henc	henc	save	2
4	pbkdf2_sha256$1000000$8nixmxxEck7vZ19fmlbbrm$v/oXMYVSPTtcSl35iEaYXNvJ5bZu9wsclShlYlnLiLE=	2026-05-28 08:39:07.229468+07	f	AlexUser	Александр	Фёдоров	hhuet@mon.com	f	t	2026-05-14 11:02:50+07	Геккон	ТОиР	Инженер	Андреевич	2
\.


--
-- Data for Name: student_groups; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.student_groups (id, student_id, group_id) FROM stdin;
\.


--
-- Data for Name: student_user_permissions; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.student_user_permissions (id, student_id, permission_id) FROM stdin;
\.


--
-- Data for Name: test; Type: TABLE DATA; Schema: public; Owner: gek
--

COPY public.test (id, title, description, time_limit, image) FROM stdin;
14	Электрика	Тест предназначен для проверки базовых и профильных знаний в области электротехники — от теоретических основ до практических навыков безопасной работы с электрооборудованием. Позволяет оценить готовность персонала к выполнению задач с учётом требований нормативных документов и стандартов безопасности.	3	tests_images/test_image_Ex5EFpe_L9SdEb3_QctFfwJ_7RKB0XA..jpg
16	Основы гидравлики для гидравликов	Тест предназначен для проверки профессиональных знаний в области гидравлических систем — от физических основ гидравлики до устройства насосов, гидромоторов, распределителей, рукавов высокого давления и арматуры. Позволяет оценить готовность персонала к обслуживанию и ремонту гидравлического оборудования.	10	tests_images/Gemini_Generated_Image_mhinadmhinadmhin.png
15	Вводная программа по эксплуатации и обслуживанию подземной самоходной техники Хенкон	Тест предназначен для проверки базовых знаний персонала, задействованного в работе с подземной самоходной техникой производства Hencon. Он поможет оценить, насколько хорошо сотрудники освоили ключевые аспекты эксплуатации и технического обслуживания машин в условиях подземных горных работ.	5	tests_images/backGround_main_HLVIB32.jpg
\.


--
-- Name: AnswerOption_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."AnswerOption_id_seq"', 505, true);


--
-- Name: Available tests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."Available tests_id_seq"', 2, true);


--
-- Name: Available tests_tests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."Available tests_tests_id_seq"', 11, true);


--
-- Name: Question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."Question_id_seq"', 134, true);


--
-- Name: UserAnswer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."UserAnswer_id_seq"', 492, true);


--
-- Name: UserTestResult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public."UserTestResult_id_seq"', 85, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 191, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- Name: gtests_usertestattempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.gtests_usertestattempt_id_seq', 97, true);


--
-- Name: student_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.student_groups_id_seq', 1, false);


--
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.student_id_seq', 6, true);


--
-- Name: student_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.student_user_permissions_id_seq', 1, false);


--
-- Name: test_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gek
--

SELECT pg_catalog.setval('public.test_id_seq', 16, true);


--
-- Name: AnswerOption AnswerOption_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."AnswerOption"
    ADD CONSTRAINT "AnswerOption_pkey" PRIMARY KEY (id);


--
-- Name: Available tests Available tests_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Available tests"
    ADD CONSTRAINT "Available tests_pkey" PRIMARY KEY (id);


--
-- Name: Available tests_tests Available tests_tests_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Available tests_tests"
    ADD CONSTRAINT "Available tests_tests_pkey" PRIMARY KEY (id);


--
-- Name: Available tests_tests Available tests_tests_studenttype_id_test_id_f81873ff_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Available tests_tests"
    ADD CONSTRAINT "Available tests_tests_studenttype_id_test_id_f81873ff_uniq" UNIQUE (studenttype_id, test_id);


--
-- Name: Question Question_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Question"
    ADD CONSTRAINT "Question_pkey" PRIMARY KEY (id);


--
-- Name: UserAnswer UserAnswer_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserAnswer"
    ADD CONSTRAINT "UserAnswer_pkey" PRIMARY KEY (id);


--
-- Name: UserTestResult UserTestResult_attempt_id_key; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserTestResult"
    ADD CONSTRAINT "UserTestResult_attempt_id_key" UNIQUE (attempt_id);


--
-- Name: UserTestResult UserTestResult_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserTestResult"
    ADD CONSTRAINT "UserTestResult_pkey" PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gtests_usertestattempt gtests_usertestattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.gtests_usertestattempt
    ADD CONSTRAINT gtests_usertestattempt_pkey PRIMARY KEY (id);


--
-- Name: student_groups student_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT student_groups_pkey PRIMARY KEY (id);


--
-- Name: student_groups student_groups_student_id_group_id_81addf69_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT student_groups_student_id_group_id_81addf69_uniq UNIQUE (student_id, group_id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- Name: student_user_permissions student_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_user_permissions
    ADD CONSTRAINT student_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: student_user_permissions student_user_permissions_student_id_permission_id_7dbf3714_uniq; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_user_permissions
    ADD CONSTRAINT student_user_permissions_student_id_permission_id_7dbf3714_uniq UNIQUE (student_id, permission_id);


--
-- Name: student student_username_key; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_username_key UNIQUE (username);


--
-- Name: test test_pkey; Type: CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);


--
-- Name: AnswerOption_question_id_1942971c; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "AnswerOption_question_id_1942971c" ON public."AnswerOption" USING btree (question_id);


--
-- Name: Available tests_tests_studenttype_id_b239b5f9; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "Available tests_tests_studenttype_id_b239b5f9" ON public."Available tests_tests" USING btree (studenttype_id);


--
-- Name: Available tests_tests_test_id_bccf598a; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "Available tests_tests_test_id_bccf598a" ON public."Available tests_tests" USING btree (test_id);


--
-- Name: Question_test_id_4cdf1744; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "Question_test_id_4cdf1744" ON public."Question" USING btree (test_id);


--
-- Name: UserAnswer_attempt_id_248cbf1b; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "UserAnswer_attempt_id_248cbf1b" ON public."UserAnswer" USING btree (attempt_id);


--
-- Name: UserAnswer_question_id_39d7cfd3; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "UserAnswer_question_id_39d7cfd3" ON public."UserAnswer" USING btree (question_id);


--
-- Name: UserAnswer_selected_option_id_7d1a2eb0; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "UserAnswer_selected_option_id_7d1a2eb0" ON public."UserAnswer" USING btree (selected_option_id);


--
-- Name: UserAnswer_user_id_50efefbd; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "UserAnswer_user_id_50efefbd" ON public."UserAnswer" USING btree (user_id);


--
-- Name: UserTestResult_user_id_d96af8c1; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX "UserTestResult_user_id_d96af8c1" ON public."UserTestResult" USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: gtests_usertestattempt_test_id_23bb81ed; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX gtests_usertestattempt_test_id_23bb81ed ON public.gtests_usertestattempt USING btree (test_id);


--
-- Name: gtests_usertestattempt_user_id_1604f605; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX gtests_usertestattempt_user_id_1604f605 ON public.gtests_usertestattempt USING btree (user_id);


--
-- Name: student_groups_group_id_0bc54d92; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_groups_group_id_0bc54d92 ON public.student_groups USING btree (group_id);


--
-- Name: student_groups_student_id_2cd9b76d; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_groups_student_id_2cd9b76d ON public.student_groups USING btree (student_id);


--
-- Name: student_student_type_id_a6a8a59d; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_student_type_id_a6a8a59d ON public.student USING btree (student_type_id);


--
-- Name: student_user_permissions_permission_id_7b58a882; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_user_permissions_permission_id_7b58a882 ON public.student_user_permissions USING btree (permission_id);


--
-- Name: student_user_permissions_student_id_e1448ffa; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_user_permissions_student_id_e1448ffa ON public.student_user_permissions USING btree (student_id);


--
-- Name: student_username_b1d1b6d7_like; Type: INDEX; Schema: public; Owner: gek
--

CREATE INDEX student_username_b1d1b6d7_like ON public.student USING btree (username varchar_pattern_ops);


--
-- Name: AnswerOption AnswerOption_question_id_1942971c_fk_Question_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."AnswerOption"
    ADD CONSTRAINT "AnswerOption_question_id_1942971c_fk_Question_id" FOREIGN KEY (question_id) REFERENCES public."Question"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Available tests_tests Available tests_test_studenttype_id_b239b5f9_fk_Available; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Available tests_tests"
    ADD CONSTRAINT "Available tests_test_studenttype_id_b239b5f9_fk_Available" FOREIGN KEY (studenttype_id) REFERENCES public."Available tests"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Available tests_tests Available tests_tests_test_id_bccf598a_fk_test_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Available tests_tests"
    ADD CONSTRAINT "Available tests_tests_test_id_bccf598a_fk_test_id" FOREIGN KEY (test_id) REFERENCES public.test(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Question Question_test_id_4cdf1744_fk_test_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."Question"
    ADD CONSTRAINT "Question_test_id_4cdf1744_fk_test_id" FOREIGN KEY (test_id) REFERENCES public.test(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserAnswer UserAnswer_attempt_id_248cbf1b_fk_gtests_usertestattempt_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserAnswer"
    ADD CONSTRAINT "UserAnswer_attempt_id_248cbf1b_fk_gtests_usertestattempt_id" FOREIGN KEY (attempt_id) REFERENCES public.gtests_usertestattempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserAnswer UserAnswer_question_id_39d7cfd3_fk_Question_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserAnswer"
    ADD CONSTRAINT "UserAnswer_question_id_39d7cfd3_fk_Question_id" FOREIGN KEY (question_id) REFERENCES public."Question"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserAnswer UserAnswer_selected_option_id_7d1a2eb0_fk_AnswerOption_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserAnswer"
    ADD CONSTRAINT "UserAnswer_selected_option_id_7d1a2eb0_fk_AnswerOption_id" FOREIGN KEY (selected_option_id) REFERENCES public."AnswerOption"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserAnswer UserAnswer_user_id_50efefbd_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserAnswer"
    ADD CONSTRAINT "UserAnswer_user_id_50efefbd_fk_student_id" FOREIGN KEY (user_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserTestResult UserTestResult_attempt_id_19f51382_fk_gtests_usertestattempt_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserTestResult"
    ADD CONSTRAINT "UserTestResult_attempt_id_19f51382_fk_gtests_usertestattempt_id" FOREIGN KEY (attempt_id) REFERENCES public.gtests_usertestattempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: UserTestResult UserTestResult_user_id_d96af8c1_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public."UserTestResult"
    ADD CONSTRAINT "UserTestResult_user_id_d96af8c1_fk_student_id" FOREIGN KEY (user_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_student_id FOREIGN KEY (user_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gtests_usertestattempt gtests_usertestattempt_test_id_23bb81ed_fk_test_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.gtests_usertestattempt
    ADD CONSTRAINT gtests_usertestattempt_test_id_23bb81ed_fk_test_id FOREIGN KEY (test_id) REFERENCES public.test(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gtests_usertestattempt gtests_usertestattempt_user_id_1604f605_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.gtests_usertestattempt
    ADD CONSTRAINT gtests_usertestattempt_user_id_1604f605_fk_student_id FOREIGN KEY (user_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_groups student_groups_group_id_0bc54d92_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT student_groups_group_id_0bc54d92_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_groups student_groups_student_id_2cd9b76d_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT student_groups_student_id_2cd9b76d_fk_student_id FOREIGN KEY (student_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student student_student_type_id_a6a8a59d_fk_Available tests_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT "student_student_type_id_a6a8a59d_fk_Available tests_id" FOREIGN KEY (student_type_id) REFERENCES public."Available tests"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_user_permissions student_user_permiss_permission_id_7b58a882_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_user_permissions
    ADD CONSTRAINT student_user_permiss_permission_id_7b58a882_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_user_permissions student_user_permissions_student_id_e1448ffa_fk_student_id; Type: FK CONSTRAINT; Schema: public; Owner: gek
--

ALTER TABLE ONLY public.student_user_permissions
    ADD CONSTRAINT student_user_permissions_student_id_e1448ffa_fk_student_id FOREIGN KEY (student_id) REFERENCES public.student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 4BrPHDkGrQfJZSCltTqtfYCRT2i5Xd82ggWqVws0lb0V4JyhcZisq6IrDNfyNrr

