# Generated by Django 5.2 on 2026-04-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttype',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимум попыток на тест'),
        ),
    ]
