# Generated by Django 5.2 on 2026-04-14 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0002_question_test_answeroption_question_test_useranswer_and_more'),
        ('main', '0002_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(blank=True, related_name='allowed_for_student_types', to='gtests.test')),
            ],
            options={
                'verbose_name': 'Доступные тесты',
                'verbose_name_plural': 'Доступные тесты',
                'db_table': 'Available tests',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.studenttype', verbose_name='Тип студента'),
        ),
    ]
