# Generated by Django 5.2 on 2026-04-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studenttype_student_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttype',
            name='student',
        ),
    ]
