"""
Django settings for HenkonKnowledgeTest project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging

# from django.conf.global_settings import LOGIN_REDIRECT_URL, LOGIN_URL, MEDIA_ROOT, MEDIA_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_$7a=_7fd=^)$+k2o(bx3!^!-l_5(sjtl3)*ci%%i(i!tfc+dc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "gtests",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "HenkonKnowledgeTest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HenkonKnowledgeTest.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "gtests",
        "USER": "gek",
        "PASSWORD": "gek",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = "main.Student"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

LOGIN_REDIRECT_URL = "main:index"
LOGIN_URL = "main:login"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)  #Если папка уже существует → ошибки не будет.


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {            #КАК будет выглядеть лог.Например:2026-05-20 | ERROR | views | line 52 | database error
        "verbose": {
            "format": (
                "{asctime} | "    # Время ошибки.
                "{levelname} | "  #Уровень ошибки:
                "{name} | "       #Имя logger.
                "{module} | "       #Имя файла Python.
                "{funcName} | "     #Имя функции.
                "line {lineno} | "      #Номер строки.ОЧЕНЬ полезно на сервере.
                "{message}"     #Текст твоего лога.
            ),
            "style": "{",
        },

        "simple": {                                                         #Красивый вывод в консоль.Например:INFO | TEST STARTED
            "format": "{levelname} | {message}",
            "style": "{",
        },
    },

    "handlers": {            # andler = куда писать лог.Например:файл консоль email telegram linux journal

        "django_file": {        # отлов ошибок Django 
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",        #Автоматически:ограничивает размеh / создаёт новые файлы
            "filename": LOG_DIR / "django_errors.log",          #Куда писать.
            "maxBytes": 1024 * 1024 * 5,                        #Максимальный размер:
            "backupCount": 5,                                   # Хранить 5 старых логов 
            "formatter": "verbose",                             #Использовать подробный формат.
        },

        "gtests_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "gtests.log",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "verbose",
        },

        "warning_file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "warnings.log",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "verbose",
        },

        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },

        "main_file": {
            "level": "INFO", # INFO и выше
            "class": "logging.handlers.RotatingFileHandler",  # Ротация логов
            "filename": LOG_DIR / "main.log",   # Файл:
                                                # logs/main.log
            "maxBytes": 1024 * 1024 * 5,     # Максимальный размер:
                                            # 5 MB
            "backupCount": 5,   # 5 резервных файлов
            "formatter": "verbose", # Подробный formatter
        },
    },

    "loggers": {

        "django": {
            "handlers": ["django_file", "console"],
            "level": "ERROR",
            "propagate": True,
        },

        "gtests": {
            "handlers": ["gtests_file", "warning_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "main": {
            "handlers": ["main_file","warning_file", "console"],
            "level": "INFO",        # INFO и выше
            "propagate": False,    # Не дублировать логи
        },

    },
}
