# Generated by Django 5.2 on 2026-04-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertestattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gtests.usertestattempt'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='gtests.usertestattempt'),
        ),
    ]
