# Generated by Django 5.2 on 2026-04-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0002_question_test_answeroption_question_test_useranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение'),
        ),
    ]
