# Generated by Django 5.2 on 2026-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0003_test_image_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='question_images/plug.jpg', null=True, upload_to='question_images/', verbose_name='Изображение'),
        ),
    ]
