# Generated by Django 5.2 on 2026-04-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0003_alter_usertestattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestattempt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
