# Generated by Django 5.2 on 2026-04-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0004_usertestattempt_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCategories',
        ),
        migrations.AlterModelOptions(
            name='usertestattempt',
            options={'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
    ]
