# Generated by Django 5.2 on 2026-05-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtests', '0005_delete_testcategories_alter_usertestattempt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'verbose_name': 'Результаты теста', 'verbose_name_plural': 'Результаты тестов | процентовка'},
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtests.answeroption'),
        ),
    ]
